name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: python -m pytest tests/unit -v

      - name: Run integration tests
        run: python -m pytest tests/integration -v

      - name: License compliance check
        run: |
          if ! grep -q "GNU General Public License v3.0" LICENSE; then
            echo "ERROR: LICENSE file missing or invalid"
            exit 1
          fi
          if ! grep -r "SPDX-License-Identifier: GPL-3.0-only" src/; then
            echo "WARNING: Source files missing SPDX headers"
          fi